language: sh

sudo: required

services:
  - docker

dist: trusty

branches:
  only:
    - master

env:
  matrix:
    - TASK=check-format
    - TASK=check-release-file
    - TASK=deploy
      stage: deploy

script:
  - make "$TASK"

stages:
  - test
  - name: deploy
    if: type = push
